---
title: "Johannes Markus Feldhege's CV"
author: Johannes Markus Feldhege
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "./data/",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================


```{r}
if(params$pdf_mode){
  cat("View this CV online with links at _https://www.johannesfeldhege.de/cv/_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://www.johannesfeldhege.de/assets/Johannes_Lebenslauf.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Language Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R packages [**pagedown**](https://github.com/rstudio/pagedown) and [[**datadrivencv**](https://github.com/nstrayer/datadrivencv). 

Source code: [github.com/jfeldhege/cv](https://github.com/jfeldhege/cv/).

Last updated on `r format(Sys.Date(), "%d.%m.%Y")`.



Main
================================================================================

Johannes Markus Feldhege {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```

Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('positions')
```


Selected Publications {data-icon=book}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('academic_articles')
```


Conference Posters and Talks {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('academic_articles')
```


Projects {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('projects')
```


```{r}
CV %<>% print_links()
```

<!-- These breaks just force a new page so section doesnt get cut off -->
<br>
